[package]
name = "kvs"
version = "0.1.0"
authors = ["DepletedPrism"]
description = "A simple key-value store in Rust"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["cargo"] }

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"